server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes: #给服务配置路由
    user-service: # 服务名
      path: /userService/** #将匹配/userService/**的请求路由到user-service服务上
    feign-service: # 服务名
      path: /feignService/**
  #禁用默认路由规则 默认路由规则会自动配置的路由以服务名称为匹配路径
  #如 user-service:
  #     path: /user-service/**
  ignored-services: user-service,feign-service
  prefix: /proxy #访问前缀
  #配置过滤敏感的请求头信息,请求内部的信息不会进入到微服务内部
  sensitive-headers: Cookie,Set-Cookie,Authorization
  #设置为true,重定向是会添加host请求头
  add-host-header: true
ribbon: #全局配置
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
management:
  endpoints:
    web:
      exposure:
        exclude: 'routes'
