server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://github.com/lichuangCN/springcloud-config.git
          username: lichuangCN
          password: 150github
          clone-on-start: true #开启启动时直接从git获取配置
          # 遗留问题：此处无法加载config文件夹下的配置文件
          search-paths: '{application}' #application占位符，表示对于不同的应用，我们从对应应用名称的子目录中搜索配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
