server:
  port: 8902
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lichuangCN/springcloud-config.git
          username: # git账号
          password: # git密码
          clone-on-start: true # 开启启动时直接从git获取配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
